services:
  wireshark:
    build:
      context: .
      dockerfile: ./Dockerfile.tools
    image: ghcr.io/patsec/uiuc-farm/tools:main
    init: true
    privileged: true # required for capturing traffic on host interfaces
    network_mode: host
    volumes:
    - ./configs/docker/tigervnc-wireshark.conf:/etc/supervisor/conf.d/tigervnc-wireshark.conf
    - ./configs/docker/wireshark.conf:/etc/supervisor/conf.d/wireshark.conf
  main-ctlr:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    cap_add:
    - NET_ADMIN # for Tailscale
    depends_on:
    - yaw-ctlr
    - anemometer
    - blade-1
    - blade-2
    - blade-3
    - opensearch
    volumes:
    - /lib/modules:/lib/modules:ro # for Tailscale
    - /dev/net/tun:/dev/net/tun    # for Tailscale
    - ./configs/ot-sim/main-controller.xml:/etc/ot-sim/config.xml
    - ./configs/ot-sim/node-red.json:/etc/node-red.json
    ports:
    - 1880:1880
    environment:
    - OTSIM_TAILSCALE_AUTHKEY=${OTSIM_TAILSCALE_AUTHKEY} # for Tailscale
    hostname: ${HOSTNAME} # for Tailscale
    networks:
      vpc:
        ipv4_address: 10.11.12.100
  yaw-ctlr:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    depends_on:
    - opensearch
    volumes:
    - ./configs/ot-sim/yaw-controller.xml:/etc/ot-sim/config.xml
    networks:
      vpc:
        ipv4_address: 10.11.12.101
  anemometer:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    depends_on:
    - opensearch
    volumes:
    - ./configs/ot-sim/anemometer.xml:/etc/ot-sim/config.xml
    - ./configs/ot-sim/weather.csv:/etc/ot-sim/data/weather.csv
    networks:
      vpc:
        ipv4_address: 10.11.12.102
  blade-1:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    depends_on:
    - opensearch
    volumes:
    - ./configs/ot-sim/blade-1.xml:/etc/ot-sim/config.xml
    networks:
      vpc:
        ipv4_address: 10.11.12.103
  blade-2:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    depends_on:
    - opensearch
    volumes:
    - ./configs/ot-sim/blade-2.xml:/etc/ot-sim/config.xml
    networks:
      vpc:
        ipv4_address: 10.11.12.104
  blade-3:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    depends_on:
    - opensearch
    volumes:
    - ./configs/ot-sim/blade-3.xml:/etc/ot-sim/config.xml
    networks:
      vpc:
        ipv4_address: 10.11.12.105
  opensearch:
    image: opensearchproject/opensearch
    init: true
    volumes:
    - ./configs/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    networks:
      vpc:
        ipv4_address: 10.11.12.150
  grafana:
    image: grafana/grafana-oss
    init: true
    depends_on:
    - opensearch
    ports:
    - 3000:3000
    volumes:
    - ./configs/grafana/plugins:/var/lib/grafana/plugins
    - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini
    - ./configs/grafana/opensearch-data-source.yml:/etc/grafana/provisioning/datasources/opensearch.yml
    - ./configs/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    - ./configs/grafana/turbine-dashboard.json:/var/lib/grafana/dashboards/turbine-dashboard.json
    networks:
      vpc:
        ipv4_address: 10.11.12.151
networks:
  vpc:
    driver: bridge
    ipam:
      config:
      - subnet: 10.11.12.0/24
        gateway: 10.11.12.1
